### ISSUE TITLE
Testing and docstring of gnsd

### ISSUE THREAD

**Issue by mforets** [RalphAS/GeneralizedNullspaces.jl#1]
Hi from here, you answered to [my question in discourse](https://discourse.julialang.org/t/jordan-form-of-a-matrix/7123/10) and i decided to try out GeneralizedNullSpaces. 

For dense matrices (say `A = randn(4, 4)`) and for custom large sparse matrices in `Float64` with off-diagonal block structure I get `V=Id` and `B=A`. I thought i would be getting a block upper-triangular matrix `B`, but i may have misunderstood the algorithm. My matrices don't have `0` as eigenvalue. When I tried it with dense matrices that i specifically construct that have some`0` eigenvalues, it worked fine. 

Another comment: in the docstring of `gnsd` it says `A = V * B * V` although it's probably a typo and it should say `A = V * B * V'`, with the conjugate transpose of `V` in the right.

**Comment by RalphAS** [comment]
A nonsingular matrix (no zero eigenvalues) has a trivial GNSD: one "block" of full size. You would need to shift (`A` to `A-λI`) for other subspaces. I wouldn't expect this algorithm to be appropriate for (singular) sparse matrices because of fill-in. I'll try to clarify the documentation.

You are quite right about the typo; thanks for the pointer.

**Comment by mforets** [comment]
Got it, thanks for the feedback.
